#!/usr/bin/env python3
"""Block unauthorized attribution or branding in SVG outputs.

Usage:
  python3 scripts/check-svg-attribution.py <svg-file>
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


SVG_NS = "{http://www.w3.org/2000/svg}"
OBSOLETE_WATERMARK_PATH_PREFIX = "M13.1671216875,2.6806859859375"
BANNED_PATTERNS = [
    re.compile(r"auto-diagram\s*生成", re.IGNORECASE),
    re.compile(r"auto diagram\s*generated", re.IGNORECASE),
    re.compile(r"generated by\s*auto-diagram", re.IGNORECASE),
    re.compile(r"generated with\s*auto-diagram", re.IGNORECASE),
    re.compile(r"made with\s*auto-diagram", re.IGNORECASE),
    re.compile(r"powered by\s*auto-diagram", re.IGNORECASE),
    re.compile(r"created by\s*auto-diagram", re.IGNORECASE),
    re.compile(r"produced by\s*auto-diagram", re.IGNORECASE),
    re.compile(r"由\s*auto-diagram\s*生成", re.IGNORECASE),
    re.compile(r"\u83dc\u5305\s*AI", re.IGNORECASE),
    re.compile(r"\u83dc\u5305AI", re.IGNORECASE),
]


def normalize_text(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip())


def normalize_path_data(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip())


def visible_text_runs(root: ET.Element) -> list[str]:
    runs: list[str] = []
    for element in root.iter():
        if element.tag != f"{SVG_NS}text":
            continue
        text = normalize_text("".join(element.itertext()))
        if text:
            runs.append(text)
    return runs


def obsolete_watermark_paths(root: ET.Element) -> list[str]:
    paths: list[str] = []
    for element in root.iter():
        if element.tag != f"{SVG_NS}path":
            continue
        path_data = normalize_path_data(element.get("d") or "")
        if path_data.startswith(OBSOLETE_WATERMARK_PATH_PREFIX):
            paths.append("[obsolete-watermark-path] legacy watermark geometry")
    return paths


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python3 scripts/check-svg-attribution.py <svg-file>")
        return 2

    svg_file = Path(sys.argv[1])
    if not svg_file.is_file():
        print(f"ERROR: File not found: {svg_file}")
        return 2

    try:
        root = ET.fromstring(svg_file.read_text(encoding="utf-8"))
    except ET.ParseError as exc:
        print(f"ERROR: Failed to parse SVG: {exc}")
        return 2

    violations: list[str] = []
    for text in visible_text_runs(root):
        normalized = normalize_text(text)
        for pattern in BANNED_PATTERNS:
            if pattern.search(normalized):
                violations.append(normalized)
                break

    violations.extend(obsolete_watermark_paths(root))

    if violations:
        print(f"ERROR: Unauthorized attribution or branding detected in {svg_file}")
        for violation in violations:
            print(f" - {violation}")
        print("Do not add generated-by text, footer signatures, branding marks, or watermark geometry inside the diagram.")
        return 1

    print(f"OK: No unauthorized attribution or branding detected in {svg_file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
